---
name: Feature Request
about: Propose a change that introduces new functionality
title: ''
labels: request
assignees: ''
---

**Is your feature request motivated by a concrete problem? Please describe.**

A clear and concise description of what the problem is. Examples:

  - "I frequently want to do X, but Auster makes it hard. It would be nice if Auster..."
  - "I want to do X but Auster makes it impossible because..."
  - "Feature Z exists, but it has these drawbacks. What if..."

  **Why this feature can't or shouldn't live outside of Auster**
  
  Auster is designed to have a small but pluggable core. Feature requests that can be implemented outside of Auster are typically declined. Make a case for why this feature can't or shouldn't be implemented outside of Auster.

  **Ideal Solution**
  
  If you have an idea for a solution, propose it with a clear and concise description.

  **Alternatives Considered**
  
  A clear and concise description of any alternative solutions or features you've considered.

  **Additional Context**
  
  Add any other context here, for example, descriptions of elegant solutions in other software.